### ISSUE TITLE
Pesquisar Oportunidades

### ISSUE THREAD

**Issue by lucassveloso** [aceleradora8/ongarium-rails#1]
[Link da história #1 na wiki](https://sites.google.com/site/softwarekaizen/projetos/turma-8-rubiteam/backlog/historia-1-pesquisar-oportunidades)

**Comment by thiagoxvo** [comment]
Pessoal, até procurei alguma coisa pra comentar, mas não encontrei.
Tudo que eu ia sugerir como melhoria vocês já fizeram durante o andamento da história.
Validada e aprovada!
